version: '3.1'
services:
  rabbitmq:
    image: "library/rabbitmq:3.7.7-management"
    restart: "no"
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "KZRDZQskRLtTQaVLXDtfGNoHcc"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"
  mssql:
    image: "microsoft/mssql-server-linux"
    restart: "no"
    volumes:
      - ./sql-data:/tmp
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "K6Zutakdo4ig7GP4VgGmnVRjLt"
      ACCEPT_EULA: "Y"
  postgres:
    image: postgres
    restart: "no"
    environment:
      POSTGRES_PASSWORD: PUg2rt6Pp8Arx7Z9FbgJLFvxEL7pZ2
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  pgadmin:
    environment:
      PGADMIN_DEFAULT_EMAIL: test@user
      PGADMIN_DEFAULT_PASSWORD: PUg2rt6Pp8Arx7Z9FbgJLFvxEL7pZ2
    links:
      - postgres
    image: dpage/pgadmin4
    ports:
      - "8080:80"
    restart: "no"
volumes:
  pgdata:
