version: '3.1'
services:
  mssql:
    image: "microsoft/mssql-server-linux"
    volumes:
      - ./sql-data:/tmp
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "K6Zutakdo4ig7GP4VgGmnVRjLt"
      ACCEPT_EULA: "Y"
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: PUg2rt6Pp8Arx7Z9FbgJLFvxEL7pZ2
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  pgadmin:
    environment:
      PGADMIN_DEFAULT_EMAIL: test@user
      PGADMIN_DEFAULT_PASSWORD: PUg2rt6Pp8Arx7Z9FbgJLFvxEL7pZ2
    links:
      - postgres
    image: dpage/pgadmin4
    ports:
      - "8080:80"
    restart: unless-stopped
volumes:
  pgdata:
