variables:
  buildConfiguration: 'Release'
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1

trigger:
  batch: true
  branches:
    include:
    - '*'
  paths:
    include:
    - /src/NuGetTrends.Scheduler/*
    - /src/NuGetTrends.Data/*
    - /src/Directory.Build.props
    - /worker-pipeline.yml
    exclude:
    - README.md

strategy:
  matrix:
    linux:
      imageName: 'ubuntu-18.04'
    mac:
      imageName: 'macOS-10.14'
    windows:
      imageName: 'windows-2019'

pool:
  vmImage: $(imageName)

steps:

- task: DotNetCoreInstaller@0
  displayName: 'Use .NET Core sdk 3.1.100'
  inputs:
    version: 3.1.100

- task: DotNetCoreCLI@1
  displayName: NuGet Restore
  inputs:
    command: restore
    projects: '**/NuGetTrends.Scheduler.csproj'

- task: DotNetCoreCLI@1
  displayName: Build
  inputs:
    projects: '**/NuGetTrends.Scheduler.csproj'
    arguments: '--configuration $(BuildConfiguration) --no-restore'

# TODO: Add tests

- task: DotNetCoreCLI@1
  displayName: Publish
  inputs:
    command: publish
    publishWebProjects: false
    projects: '**/NuGetTrends.Scheduler.csproj'
    arguments: '-c $(BuildConfiguration) -o $(Build.ArtifactStagingDirectory) --no-build'
